version: '3.8'
services: 
    web: 
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports: 
            - 8000:8000
    # api:
    #     container_name: api-container
    #     restart: always
    #     build: ./backend/
    #     ports: 
    #         - "8081:8081"
    # client:
    #     container_name: client-container
    #     restart: always
    #     build: ./frontend/
    #     ports: 
    #         - "8080:8080"
    #     depends_on: 
    #         - api