version: '3.8'
services: 
    client:
        container_name: client-container
        restart: always
        build: ./wiki-frontend/
        ports: 
            - "8080:8080"
        depends_on: 
            - api
    api:
        container_name: api-container
        restart: always
        build: ./wiki-backend/
        ports: 
            - "8081:8081"